// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steamnetworkingsockets_messages_certs.proto

#ifndef PROTOBUF_steamnetworkingsockets_5fmessages_5fcerts_2eproto__INCLUDED
#define PROTOBUF_steamnetworkingsockets_5fmessages_5fcerts_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsCMsgSteamNetworkingIdentityLegacyBinaryImpl();
void InitDefaultsCMsgSteamNetworkingIdentityLegacyBinary();
void InitDefaultsCMsgSteamDatagramCertificateImpl();
void InitDefaultsCMsgSteamDatagramCertificate();
void InitDefaultsCMsgSteamDatagramCertificateSignedImpl();
void InitDefaultsCMsgSteamDatagramCertificateSigned();
void InitDefaultsCMsgSteamDatagramCertificateRequestImpl();
void InitDefaultsCMsgSteamDatagramCertificateRequest();
inline void InitDefaults() {
  InitDefaultsCMsgSteamNetworkingIdentityLegacyBinary();
  InitDefaultsCMsgSteamDatagramCertificate();
  InitDefaultsCMsgSteamDatagramCertificateSigned();
  InitDefaultsCMsgSteamDatagramCertificateRequest();
}
}  // namespace protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto
class CMsgSteamDatagramCertificate;
class CMsgSteamDatagramCertificateDefaultTypeInternal;
extern CMsgSteamDatagramCertificateDefaultTypeInternal _CMsgSteamDatagramCertificate_default_instance_;
class CMsgSteamDatagramCertificateRequest;
class CMsgSteamDatagramCertificateRequestDefaultTypeInternal;
extern CMsgSteamDatagramCertificateRequestDefaultTypeInternal _CMsgSteamDatagramCertificateRequest_default_instance_;
class CMsgSteamDatagramCertificateSigned;
class CMsgSteamDatagramCertificateSignedDefaultTypeInternal;
extern CMsgSteamDatagramCertificateSignedDefaultTypeInternal _CMsgSteamDatagramCertificateSigned_default_instance_;
class CMsgSteamNetworkingIdentityLegacyBinary;
class CMsgSteamNetworkingIdentityLegacyBinaryDefaultTypeInternal;
extern CMsgSteamNetworkingIdentityLegacyBinaryDefaultTypeInternal _CMsgSteamNetworkingIdentityLegacyBinary_default_instance_;

enum CMsgSteamDatagramCertificate_EKeyType {
  CMsgSteamDatagramCertificate_EKeyType_INVALID = 0,
  CMsgSteamDatagramCertificate_EKeyType_ED25519 = 1
};
bool CMsgSteamDatagramCertificate_EKeyType_IsValid(int value);
const CMsgSteamDatagramCertificate_EKeyType CMsgSteamDatagramCertificate_EKeyType_EKeyType_MIN = CMsgSteamDatagramCertificate_EKeyType_INVALID;
const CMsgSteamDatagramCertificate_EKeyType CMsgSteamDatagramCertificate_EKeyType_EKeyType_MAX = CMsgSteamDatagramCertificate_EKeyType_ED25519;
const int CMsgSteamDatagramCertificate_EKeyType_EKeyType_ARRAYSIZE = CMsgSteamDatagramCertificate_EKeyType_EKeyType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CMsgSteamDatagramCertificate_EKeyType_descriptor();
inline const ::std::string& CMsgSteamDatagramCertificate_EKeyType_Name(CMsgSteamDatagramCertificate_EKeyType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CMsgSteamDatagramCertificate_EKeyType_descriptor(), value);
}
inline bool CMsgSteamDatagramCertificate_EKeyType_Parse(
    const ::std::string& name, CMsgSteamDatagramCertificate_EKeyType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CMsgSteamDatagramCertificate_EKeyType>(
    CMsgSteamDatagramCertificate_EKeyType_descriptor(), name, value);
}
// ===================================================================

class CMsgSteamNetworkingIdentityLegacyBinary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMsgSteamNetworkingIdentityLegacyBinary) */ {
 public:
  CMsgSteamNetworkingIdentityLegacyBinary();
  virtual ~CMsgSteamNetworkingIdentityLegacyBinary();

  CMsgSteamNetworkingIdentityLegacyBinary(const CMsgSteamNetworkingIdentityLegacyBinary& from);

  inline CMsgSteamNetworkingIdentityLegacyBinary& operator=(const CMsgSteamNetworkingIdentityLegacyBinary& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CMsgSteamNetworkingIdentityLegacyBinary(CMsgSteamNetworkingIdentityLegacyBinary&& from) noexcept
    : CMsgSteamNetworkingIdentityLegacyBinary() {
    *this = ::std::move(from);
  }

  inline CMsgSteamNetworkingIdentityLegacyBinary& operator=(CMsgSteamNetworkingIdentityLegacyBinary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgSteamNetworkingIdentityLegacyBinary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgSteamNetworkingIdentityLegacyBinary* internal_default_instance() {
    return reinterpret_cast<const CMsgSteamNetworkingIdentityLegacyBinary*>(
               &_CMsgSteamNetworkingIdentityLegacyBinary_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CMsgSteamNetworkingIdentityLegacyBinary* other);
  friend void swap(CMsgSteamNetworkingIdentityLegacyBinary& a, CMsgSteamNetworkingIdentityLegacyBinary& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMsgSteamNetworkingIdentityLegacyBinary* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgSteamNetworkingIdentityLegacyBinary* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgSteamNetworkingIdentityLegacyBinary& from);
  void MergeFrom(const CMsgSteamNetworkingIdentityLegacyBinary& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgSteamNetworkingIdentityLegacyBinary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes generic_bytes = 2;
  bool has_generic_bytes() const;
  void clear_generic_bytes();
  static const int kGenericBytesFieldNumber = 2;
  const ::std::string& generic_bytes() const;
  void set_generic_bytes(const ::std::string& value);
  #if LANG_CXX11
  void set_generic_bytes(::std::string&& value);
  #endif
  void set_generic_bytes(const char* value);
  void set_generic_bytes(const void* value, size_t size);
  ::std::string* mutable_generic_bytes();
  ::std::string* release_generic_bytes();
  void set_allocated_generic_bytes(::std::string* generic_bytes);

  // optional string generic_string = 3;
  bool has_generic_string() const;
  void clear_generic_string();
  static const int kGenericStringFieldNumber = 3;
  const ::std::string& generic_string() const;
  void set_generic_string(const ::std::string& value);
  #if LANG_CXX11
  void set_generic_string(::std::string&& value);
  #endif
  void set_generic_string(const char* value);
  void set_generic_string(const char* value, size_t size);
  ::std::string* mutable_generic_string();
  ::std::string* release_generic_string();
  void set_allocated_generic_string(::std::string* generic_string);

  // optional bytes ipv6_and_port = 4;
  bool has_ipv6_and_port() const;
  void clear_ipv6_and_port();
  static const int kIpv6AndPortFieldNumber = 4;
  const ::std::string& ipv6_and_port() const;
  void set_ipv6_and_port(const ::std::string& value);
  #if LANG_CXX11
  void set_ipv6_and_port(::std::string&& value);
  #endif
  void set_ipv6_and_port(const char* value);
  void set_ipv6_and_port(const void* value, size_t size);
  ::std::string* mutable_ipv6_and_port();
  ::std::string* release_ipv6_and_port();
  void set_allocated_ipv6_and_port(::std::string* ipv6_and_port);

  // optional fixed64 steam_id = 16;
  bool has_steam_id() const;
  void clear_steam_id();
  static const int kSteamIdFieldNumber = 16;
  ::google::protobuf::uint64 steam_id() const;
  void set_steam_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:CMsgSteamNetworkingIdentityLegacyBinary)
 private:
  void set_has_steam_id();
  void clear_has_steam_id();
  void set_has_generic_bytes();
  void clear_has_generic_bytes();
  void set_has_generic_string();
  void clear_has_generic_string();
  void set_has_ipv6_and_port();
  void clear_has_ipv6_and_port();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr generic_bytes_;
  ::google::protobuf::internal::ArenaStringPtr generic_string_;
  ::google::protobuf::internal::ArenaStringPtr ipv6_and_port_;
  ::google::protobuf::uint64 steam_id_;
  friend struct ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::TableStruct;
  friend void ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::InitDefaultsCMsgSteamNetworkingIdentityLegacyBinaryImpl();
};
// -------------------------------------------------------------------

class CMsgSteamDatagramCertificate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMsgSteamDatagramCertificate) */ {
 public:
  CMsgSteamDatagramCertificate();
  virtual ~CMsgSteamDatagramCertificate();

  CMsgSteamDatagramCertificate(const CMsgSteamDatagramCertificate& from);

  inline CMsgSteamDatagramCertificate& operator=(const CMsgSteamDatagramCertificate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CMsgSteamDatagramCertificate(CMsgSteamDatagramCertificate&& from) noexcept
    : CMsgSteamDatagramCertificate() {
    *this = ::std::move(from);
  }

  inline CMsgSteamDatagramCertificate& operator=(CMsgSteamDatagramCertificate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgSteamDatagramCertificate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgSteamDatagramCertificate* internal_default_instance() {
    return reinterpret_cast<const CMsgSteamDatagramCertificate*>(
               &_CMsgSteamDatagramCertificate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(CMsgSteamDatagramCertificate* other);
  friend void swap(CMsgSteamDatagramCertificate& a, CMsgSteamDatagramCertificate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMsgSteamDatagramCertificate* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgSteamDatagramCertificate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgSteamDatagramCertificate& from);
  void MergeFrom(const CMsgSteamDatagramCertificate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgSteamDatagramCertificate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CMsgSteamDatagramCertificate_EKeyType EKeyType;
  static const EKeyType INVALID =
    CMsgSteamDatagramCertificate_EKeyType_INVALID;
  static const EKeyType ED25519 =
    CMsgSteamDatagramCertificate_EKeyType_ED25519;
  static inline bool EKeyType_IsValid(int value) {
    return CMsgSteamDatagramCertificate_EKeyType_IsValid(value);
  }
  static const EKeyType EKeyType_MIN =
    CMsgSteamDatagramCertificate_EKeyType_EKeyType_MIN;
  static const EKeyType EKeyType_MAX =
    CMsgSteamDatagramCertificate_EKeyType_EKeyType_MAX;
  static const int EKeyType_ARRAYSIZE =
    CMsgSteamDatagramCertificate_EKeyType_EKeyType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  EKeyType_descriptor() {
    return CMsgSteamDatagramCertificate_EKeyType_descriptor();
  }
  static inline const ::std::string& EKeyType_Name(EKeyType value) {
    return CMsgSteamDatagramCertificate_EKeyType_Name(value);
  }
  static inline bool EKeyType_Parse(const ::std::string& name,
      EKeyType* value) {
    return CMsgSteamDatagramCertificate_EKeyType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated fixed32 gameserver_datacenter_ids = 5;
  int gameserver_datacenter_ids_size() const;
  void clear_gameserver_datacenter_ids();
  static const int kGameserverDatacenterIdsFieldNumber = 5;
  ::google::protobuf::uint32 gameserver_datacenter_ids(int index) const;
  void set_gameserver_datacenter_ids(int index, ::google::protobuf::uint32 value);
  void add_gameserver_datacenter_ids(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      gameserver_datacenter_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_gameserver_datacenter_ids();

  // repeated uint32 app_ids = 10;
  int app_ids_size() const;
  void clear_app_ids();
  static const int kAppIdsFieldNumber = 10;
  ::google::protobuf::uint32 app_ids(int index) const;
  void set_app_ids(int index, ::google::protobuf::uint32 value);
  void add_app_ids(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      app_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_app_ids();

  // optional bytes key_data = 2;
  bool has_key_data() const;
  void clear_key_data();
  static const int kKeyDataFieldNumber = 2;
  const ::std::string& key_data() const;
  void set_key_data(const ::std::string& value);
  #if LANG_CXX11
  void set_key_data(::std::string&& value);
  #endif
  void set_key_data(const char* value);
  void set_key_data(const void* value, size_t size);
  ::std::string* mutable_key_data();
  ::std::string* release_key_data();
  void set_allocated_key_data(::std::string* key_data);

  // optional string identity_string = 12;
  bool has_identity_string() const;
  void clear_identity_string();
  static const int kIdentityStringFieldNumber = 12;
  const ::std::string& identity_string() const;
  void set_identity_string(const ::std::string& value);
  #if LANG_CXX11
  void set_identity_string(::std::string&& value);
  #endif
  void set_identity_string(const char* value);
  void set_identity_string(const char* value, size_t size);
  ::std::string* mutable_identity_string();
  ::std::string* release_identity_string();
  void set_allocated_identity_string(::std::string* identity_string);

  // optional .CMsgSteamNetworkingIdentityLegacyBinary legacy_identity_binary = 11;
  bool has_legacy_identity_binary() const;
  void clear_legacy_identity_binary();
  static const int kLegacyIdentityBinaryFieldNumber = 11;
  const ::CMsgSteamNetworkingIdentityLegacyBinary& legacy_identity_binary() const;
  ::CMsgSteamNetworkingIdentityLegacyBinary* release_legacy_identity_binary();
  ::CMsgSteamNetworkingIdentityLegacyBinary* mutable_legacy_identity_binary();
  void set_allocated_legacy_identity_binary(::CMsgSteamNetworkingIdentityLegacyBinary* legacy_identity_binary);

  // optional fixed64 legacy_steam_id = 4;
  bool has_legacy_steam_id() const;
  void clear_legacy_steam_id();
  static const int kLegacySteamIdFieldNumber = 4;
  ::google::protobuf::uint64 legacy_steam_id() const;
  void set_legacy_steam_id(::google::protobuf::uint64 value);

  // optional .CMsgSteamDatagramCertificate.EKeyType key_type = 1;
  bool has_key_type() const;
  void clear_key_type();
  static const int kKeyTypeFieldNumber = 1;
  ::CMsgSteamDatagramCertificate_EKeyType key_type() const;
  void set_key_type(::CMsgSteamDatagramCertificate_EKeyType value);

  // optional fixed32 time_created = 8;
  bool has_time_created() const;
  void clear_time_created();
  static const int kTimeCreatedFieldNumber = 8;
  ::google::protobuf::uint32 time_created() const;
  void set_time_created(::google::protobuf::uint32 value);

  // optional fixed32 time_expiry = 9;
  bool has_time_expiry() const;
  void clear_time_expiry();
  static const int kTimeExpiryFieldNumber = 9;
  ::google::protobuf::uint32 time_expiry() const;
  void set_time_expiry(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CMsgSteamDatagramCertificate)
 private:
  void set_has_key_type();
  void clear_has_key_type();
  void set_has_key_data();
  void clear_has_key_data();
  void set_has_legacy_steam_id();
  void clear_has_legacy_steam_id();
  void set_has_legacy_identity_binary();
  void clear_has_legacy_identity_binary();
  void set_has_identity_string();
  void clear_has_identity_string();
  void set_has_time_created();
  void clear_has_time_created();
  void set_has_time_expiry();
  void clear_has_time_expiry();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > gameserver_datacenter_ids_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > app_ids_;
  ::google::protobuf::internal::ArenaStringPtr key_data_;
  ::google::protobuf::internal::ArenaStringPtr identity_string_;
  ::CMsgSteamNetworkingIdentityLegacyBinary* legacy_identity_binary_;
  ::google::protobuf::uint64 legacy_steam_id_;
  int key_type_;
  ::google::protobuf::uint32 time_created_;
  ::google::protobuf::uint32 time_expiry_;
  friend struct ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::TableStruct;
  friend void ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::InitDefaultsCMsgSteamDatagramCertificateImpl();
};
// -------------------------------------------------------------------

class CMsgSteamDatagramCertificateSigned : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMsgSteamDatagramCertificateSigned) */ {
 public:
  CMsgSteamDatagramCertificateSigned();
  virtual ~CMsgSteamDatagramCertificateSigned();

  CMsgSteamDatagramCertificateSigned(const CMsgSteamDatagramCertificateSigned& from);

  inline CMsgSteamDatagramCertificateSigned& operator=(const CMsgSteamDatagramCertificateSigned& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CMsgSteamDatagramCertificateSigned(CMsgSteamDatagramCertificateSigned&& from) noexcept
    : CMsgSteamDatagramCertificateSigned() {
    *this = ::std::move(from);
  }

  inline CMsgSteamDatagramCertificateSigned& operator=(CMsgSteamDatagramCertificateSigned&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgSteamDatagramCertificateSigned& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgSteamDatagramCertificateSigned* internal_default_instance() {
    return reinterpret_cast<const CMsgSteamDatagramCertificateSigned*>(
               &_CMsgSteamDatagramCertificateSigned_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(CMsgSteamDatagramCertificateSigned* other);
  friend void swap(CMsgSteamDatagramCertificateSigned& a, CMsgSteamDatagramCertificateSigned& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMsgSteamDatagramCertificateSigned* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgSteamDatagramCertificateSigned* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgSteamDatagramCertificateSigned& from);
  void MergeFrom(const CMsgSteamDatagramCertificateSigned& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgSteamDatagramCertificateSigned* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes private_key_data = 1;
  bool has_private_key_data() const;
  void clear_private_key_data();
  static const int kPrivateKeyDataFieldNumber = 1;
  const ::std::string& private_key_data() const;
  void set_private_key_data(const ::std::string& value);
  #if LANG_CXX11
  void set_private_key_data(::std::string&& value);
  #endif
  void set_private_key_data(const char* value);
  void set_private_key_data(const void* value, size_t size);
  ::std::string* mutable_private_key_data();
  ::std::string* release_private_key_data();
  void set_allocated_private_key_data(::std::string* private_key_data);

  // optional bytes cert = 4;
  bool has_cert() const;
  void clear_cert();
  static const int kCertFieldNumber = 4;
  const ::std::string& cert() const;
  void set_cert(const ::std::string& value);
  #if LANG_CXX11
  void set_cert(::std::string&& value);
  #endif
  void set_cert(const char* value);
  void set_cert(const void* value, size_t size);
  ::std::string* mutable_cert();
  ::std::string* release_cert();
  void set_allocated_cert(::std::string* cert);

  // optional bytes ca_signature = 6;
  bool has_ca_signature() const;
  void clear_ca_signature();
  static const int kCaSignatureFieldNumber = 6;
  const ::std::string& ca_signature() const;
  void set_ca_signature(const ::std::string& value);
  #if LANG_CXX11
  void set_ca_signature(::std::string&& value);
  #endif
  void set_ca_signature(const char* value);
  void set_ca_signature(const void* value, size_t size);
  ::std::string* mutable_ca_signature();
  ::std::string* release_ca_signature();
  void set_allocated_ca_signature(::std::string* ca_signature);

  // optional fixed64 ca_key_id = 5;
  bool has_ca_key_id() const;
  void clear_ca_key_id();
  static const int kCaKeyIdFieldNumber = 5;
  ::google::protobuf::uint64 ca_key_id() const;
  void set_ca_key_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:CMsgSteamDatagramCertificateSigned)
 private:
  void set_has_cert();
  void clear_has_cert();
  void set_has_ca_key_id();
  void clear_has_ca_key_id();
  void set_has_ca_signature();
  void clear_has_ca_signature();
  void set_has_private_key_data();
  void clear_has_private_key_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr private_key_data_;
  ::google::protobuf::internal::ArenaStringPtr cert_;
  ::google::protobuf::internal::ArenaStringPtr ca_signature_;
  ::google::protobuf::uint64 ca_key_id_;
  friend struct ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::TableStruct;
  friend void ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::InitDefaultsCMsgSteamDatagramCertificateSignedImpl();
};
// -------------------------------------------------------------------

class CMsgSteamDatagramCertificateRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMsgSteamDatagramCertificateRequest) */ {
 public:
  CMsgSteamDatagramCertificateRequest();
  virtual ~CMsgSteamDatagramCertificateRequest();

  CMsgSteamDatagramCertificateRequest(const CMsgSteamDatagramCertificateRequest& from);

  inline CMsgSteamDatagramCertificateRequest& operator=(const CMsgSteamDatagramCertificateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CMsgSteamDatagramCertificateRequest(CMsgSteamDatagramCertificateRequest&& from) noexcept
    : CMsgSteamDatagramCertificateRequest() {
    *this = ::std::move(from);
  }

  inline CMsgSteamDatagramCertificateRequest& operator=(CMsgSteamDatagramCertificateRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgSteamDatagramCertificateRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgSteamDatagramCertificateRequest* internal_default_instance() {
    return reinterpret_cast<const CMsgSteamDatagramCertificateRequest*>(
               &_CMsgSteamDatagramCertificateRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(CMsgSteamDatagramCertificateRequest* other);
  friend void swap(CMsgSteamDatagramCertificateRequest& a, CMsgSteamDatagramCertificateRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMsgSteamDatagramCertificateRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgSteamDatagramCertificateRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgSteamDatagramCertificateRequest& from);
  void MergeFrom(const CMsgSteamDatagramCertificateRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgSteamDatagramCertificateRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CMsgSteamDatagramCertificate cert = 1;
  bool has_cert() const;
  void clear_cert();
  static const int kCertFieldNumber = 1;
  const ::CMsgSteamDatagramCertificate& cert() const;
  ::CMsgSteamDatagramCertificate* release_cert();
  ::CMsgSteamDatagramCertificate* mutable_cert();
  void set_allocated_cert(::CMsgSteamDatagramCertificate* cert);

  // @@protoc_insertion_point(class_scope:CMsgSteamDatagramCertificateRequest)
 private:
  void set_has_cert();
  void clear_has_cert();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::CMsgSteamDatagramCertificate* cert_;
  friend struct ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::TableStruct;
  friend void ::protobuf_steamnetworkingsockets_5fmessages_5fcerts_2eproto::InitDefaultsCMsgSteamDatagramCertificateRequestImpl();
};
// ===================================================================


// ===================================================================

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgSteamNetworkingIdentityLegacyBinary

// optional fixed64 steam_id = 16;
inline bool CMsgSteamNetworkingIdentityLegacyBinary::has_steam_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_has_steam_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_has_steam_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_steam_id() {
  steam_id_ = GOOGLE_ULONGLONG(0);
  clear_has_steam_id();
}
inline ::google::protobuf::uint64 CMsgSteamNetworkingIdentityLegacyBinary::steam_id() const {
  // @@protoc_insertion_point(field_get:CMsgSteamNetworkingIdentityLegacyBinary.steam_id)
  return steam_id_;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_steam_id(::google::protobuf::uint64 value) {
  set_has_steam_id();
  steam_id_ = value;
  // @@protoc_insertion_point(field_set:CMsgSteamNetworkingIdentityLegacyBinary.steam_id)
}

// optional bytes generic_bytes = 2;
inline bool CMsgSteamNetworkingIdentityLegacyBinary::has_generic_bytes() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_has_generic_bytes() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_has_generic_bytes() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_generic_bytes() {
  generic_bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_generic_bytes();
}
inline const ::std::string& CMsgSteamNetworkingIdentityLegacyBinary::generic_bytes() const {
  // @@protoc_insertion_point(field_get:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
  return generic_bytes_.GetNoArena();
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_bytes(const ::std::string& value) {
  set_has_generic_bytes();
  generic_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
}
#if LANG_CXX11
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_bytes(::std::string&& value) {
  set_has_generic_bytes();
  generic_bytes_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
}
#endif
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_bytes(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_generic_bytes();
  generic_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_bytes(const void* value, size_t size) {
  set_has_generic_bytes();
  generic_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
}
inline ::std::string* CMsgSteamNetworkingIdentityLegacyBinary::mutable_generic_bytes() {
  set_has_generic_bytes();
  // @@protoc_insertion_point(field_mutable:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
  return generic_bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamNetworkingIdentityLegacyBinary::release_generic_bytes() {
  // @@protoc_insertion_point(field_release:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
  clear_has_generic_bytes();
  return generic_bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_allocated_generic_bytes(::std::string* generic_bytes) {
  if (generic_bytes != NULL) {
    set_has_generic_bytes();
  } else {
    clear_has_generic_bytes();
  }
  generic_bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), generic_bytes);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamNetworkingIdentityLegacyBinary.generic_bytes)
}

// optional string generic_string = 3;
inline bool CMsgSteamNetworkingIdentityLegacyBinary::has_generic_string() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_has_generic_string() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_has_generic_string() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_generic_string() {
  generic_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_generic_string();
}
inline const ::std::string& CMsgSteamNetworkingIdentityLegacyBinary::generic_string() const {
  // @@protoc_insertion_point(field_get:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
  return generic_string_.GetNoArena();
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_string(const ::std::string& value) {
  set_has_generic_string();
  generic_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
}
#if LANG_CXX11
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_string(::std::string&& value) {
  set_has_generic_string();
  generic_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
}
#endif
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_generic_string();
  generic_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_generic_string(const char* value, size_t size) {
  set_has_generic_string();
  generic_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
}
inline ::std::string* CMsgSteamNetworkingIdentityLegacyBinary::mutable_generic_string() {
  set_has_generic_string();
  // @@protoc_insertion_point(field_mutable:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
  return generic_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamNetworkingIdentityLegacyBinary::release_generic_string() {
  // @@protoc_insertion_point(field_release:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
  clear_has_generic_string();
  return generic_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_allocated_generic_string(::std::string* generic_string) {
  if (generic_string != NULL) {
    set_has_generic_string();
  } else {
    clear_has_generic_string();
  }
  generic_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), generic_string);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamNetworkingIdentityLegacyBinary.generic_string)
}

// optional bytes ipv6_and_port = 4;
inline bool CMsgSteamNetworkingIdentityLegacyBinary::has_ipv6_and_port() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_has_ipv6_and_port() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_has_ipv6_and_port() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::clear_ipv6_and_port() {
  ipv6_and_port_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ipv6_and_port();
}
inline const ::std::string& CMsgSteamNetworkingIdentityLegacyBinary::ipv6_and_port() const {
  // @@protoc_insertion_point(field_get:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
  return ipv6_and_port_.GetNoArena();
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_ipv6_and_port(const ::std::string& value) {
  set_has_ipv6_and_port();
  ipv6_and_port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
}
#if LANG_CXX11
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_ipv6_and_port(::std::string&& value) {
  set_has_ipv6_and_port();
  ipv6_and_port_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
}
#endif
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_ipv6_and_port(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_ipv6_and_port();
  ipv6_and_port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_ipv6_and_port(const void* value, size_t size) {
  set_has_ipv6_and_port();
  ipv6_and_port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
}
inline ::std::string* CMsgSteamNetworkingIdentityLegacyBinary::mutable_ipv6_and_port() {
  set_has_ipv6_and_port();
  // @@protoc_insertion_point(field_mutable:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
  return ipv6_and_port_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamNetworkingIdentityLegacyBinary::release_ipv6_and_port() {
  // @@protoc_insertion_point(field_release:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
  clear_has_ipv6_and_port();
  return ipv6_and_port_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamNetworkingIdentityLegacyBinary::set_allocated_ipv6_and_port(::std::string* ipv6_and_port) {
  if (ipv6_and_port != NULL) {
    set_has_ipv6_and_port();
  } else {
    clear_has_ipv6_and_port();
  }
  ipv6_and_port_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ipv6_and_port);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamNetworkingIdentityLegacyBinary.ipv6_and_port)
}

// -------------------------------------------------------------------

// CMsgSteamDatagramCertificate

// optional .CMsgSteamDatagramCertificate.EKeyType key_type = 1;
inline bool CMsgSteamDatagramCertificate::has_key_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_key_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgSteamDatagramCertificate::clear_has_key_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgSteamDatagramCertificate::clear_key_type() {
  key_type_ = 0;
  clear_has_key_type();
}
inline ::CMsgSteamDatagramCertificate_EKeyType CMsgSteamDatagramCertificate::key_type() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.key_type)
  return static_cast< ::CMsgSteamDatagramCertificate_EKeyType >(key_type_);
}
inline void CMsgSteamDatagramCertificate::set_key_type(::CMsgSteamDatagramCertificate_EKeyType value) {
  assert(::CMsgSteamDatagramCertificate_EKeyType_IsValid(value));
  set_has_key_type();
  key_type_ = value;
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.key_type)
}

// optional bytes key_data = 2;
inline bool CMsgSteamDatagramCertificate::has_key_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_key_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgSteamDatagramCertificate::clear_has_key_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgSteamDatagramCertificate::clear_key_data() {
  key_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key_data();
}
inline const ::std::string& CMsgSteamDatagramCertificate::key_data() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.key_data)
  return key_data_.GetNoArena();
}
inline void CMsgSteamDatagramCertificate::set_key_data(const ::std::string& value) {
  set_has_key_data();
  key_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.key_data)
}
#if LANG_CXX11
inline void CMsgSteamDatagramCertificate::set_key_data(::std::string&& value) {
  set_has_key_data();
  key_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamDatagramCertificate.key_data)
}
#endif
inline void CMsgSteamDatagramCertificate::set_key_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_key_data();
  key_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamDatagramCertificate.key_data)
}
inline void CMsgSteamDatagramCertificate::set_key_data(const void* value, size_t size) {
  set_has_key_data();
  key_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamDatagramCertificate.key_data)
}
inline ::std::string* CMsgSteamDatagramCertificate::mutable_key_data() {
  set_has_key_data();
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificate.key_data)
  return key_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamDatagramCertificate::release_key_data() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificate.key_data)
  clear_has_key_data();
  return key_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamDatagramCertificate::set_allocated_key_data(::std::string* key_data) {
  if (key_data != NULL) {
    set_has_key_data();
  } else {
    clear_has_key_data();
  }
  key_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key_data);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificate.key_data)
}

// optional fixed64 legacy_steam_id = 4;
inline bool CMsgSteamDatagramCertificate::has_legacy_steam_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_legacy_steam_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgSteamDatagramCertificate::clear_has_legacy_steam_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgSteamDatagramCertificate::clear_legacy_steam_id() {
  legacy_steam_id_ = GOOGLE_ULONGLONG(0);
  clear_has_legacy_steam_id();
}
inline ::google::protobuf::uint64 CMsgSteamDatagramCertificate::legacy_steam_id() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.legacy_steam_id)
  return legacy_steam_id_;
}
inline void CMsgSteamDatagramCertificate::set_legacy_steam_id(::google::protobuf::uint64 value) {
  set_has_legacy_steam_id();
  legacy_steam_id_ = value;
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.legacy_steam_id)
}

// optional .CMsgSteamNetworkingIdentityLegacyBinary legacy_identity_binary = 11;
inline bool CMsgSteamDatagramCertificate::has_legacy_identity_binary() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_legacy_identity_binary() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgSteamDatagramCertificate::clear_has_legacy_identity_binary() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgSteamDatagramCertificate::clear_legacy_identity_binary() {
  if (legacy_identity_binary_ != NULL) legacy_identity_binary_->Clear();
  clear_has_legacy_identity_binary();
}
inline const ::CMsgSteamNetworkingIdentityLegacyBinary& CMsgSteamDatagramCertificate::legacy_identity_binary() const {
  const ::CMsgSteamNetworkingIdentityLegacyBinary* p = legacy_identity_binary_;
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.legacy_identity_binary)
  return p != NULL ? *p : *reinterpret_cast<const ::CMsgSteamNetworkingIdentityLegacyBinary*>(
      &::_CMsgSteamNetworkingIdentityLegacyBinary_default_instance_);
}
inline ::CMsgSteamNetworkingIdentityLegacyBinary* CMsgSteamDatagramCertificate::release_legacy_identity_binary() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificate.legacy_identity_binary)
  clear_has_legacy_identity_binary();
  ::CMsgSteamNetworkingIdentityLegacyBinary* temp = legacy_identity_binary_;
  legacy_identity_binary_ = NULL;
  return temp;
}
inline ::CMsgSteamNetworkingIdentityLegacyBinary* CMsgSteamDatagramCertificate::mutable_legacy_identity_binary() {
  set_has_legacy_identity_binary();
  if (legacy_identity_binary_ == NULL) {
    legacy_identity_binary_ = new ::CMsgSteamNetworkingIdentityLegacyBinary;
  }
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificate.legacy_identity_binary)
  return legacy_identity_binary_;
}
inline void CMsgSteamDatagramCertificate::set_allocated_legacy_identity_binary(::CMsgSteamNetworkingIdentityLegacyBinary* legacy_identity_binary) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete legacy_identity_binary_;
  }
  if (legacy_identity_binary) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      legacy_identity_binary = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, legacy_identity_binary, submessage_arena);
    }
    set_has_legacy_identity_binary();
  } else {
    clear_has_legacy_identity_binary();
  }
  legacy_identity_binary_ = legacy_identity_binary;
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificate.legacy_identity_binary)
}

// optional string identity_string = 12;
inline bool CMsgSteamDatagramCertificate::has_identity_string() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_identity_string() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgSteamDatagramCertificate::clear_has_identity_string() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgSteamDatagramCertificate::clear_identity_string() {
  identity_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_identity_string();
}
inline const ::std::string& CMsgSteamDatagramCertificate::identity_string() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.identity_string)
  return identity_string_.GetNoArena();
}
inline void CMsgSteamDatagramCertificate::set_identity_string(const ::std::string& value) {
  set_has_identity_string();
  identity_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.identity_string)
}
#if LANG_CXX11
inline void CMsgSteamDatagramCertificate::set_identity_string(::std::string&& value) {
  set_has_identity_string();
  identity_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamDatagramCertificate.identity_string)
}
#endif
inline void CMsgSteamDatagramCertificate::set_identity_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_identity_string();
  identity_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamDatagramCertificate.identity_string)
}
inline void CMsgSteamDatagramCertificate::set_identity_string(const char* value, size_t size) {
  set_has_identity_string();
  identity_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamDatagramCertificate.identity_string)
}
inline ::std::string* CMsgSteamDatagramCertificate::mutable_identity_string() {
  set_has_identity_string();
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificate.identity_string)
  return identity_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamDatagramCertificate::release_identity_string() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificate.identity_string)
  clear_has_identity_string();
  return identity_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamDatagramCertificate::set_allocated_identity_string(::std::string* identity_string) {
  if (identity_string != NULL) {
    set_has_identity_string();
  } else {
    clear_has_identity_string();
  }
  identity_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), identity_string);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificate.identity_string)
}

// repeated fixed32 gameserver_datacenter_ids = 5;
inline int CMsgSteamDatagramCertificate::gameserver_datacenter_ids_size() const {
  return gameserver_datacenter_ids_.size();
}
inline void CMsgSteamDatagramCertificate::clear_gameserver_datacenter_ids() {
  gameserver_datacenter_ids_.Clear();
}
inline ::google::protobuf::uint32 CMsgSteamDatagramCertificate::gameserver_datacenter_ids(int index) const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.gameserver_datacenter_ids)
  return gameserver_datacenter_ids_.Get(index);
}
inline void CMsgSteamDatagramCertificate::set_gameserver_datacenter_ids(int index, ::google::protobuf::uint32 value) {
  gameserver_datacenter_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.gameserver_datacenter_ids)
}
inline void CMsgSteamDatagramCertificate::add_gameserver_datacenter_ids(::google::protobuf::uint32 value) {
  gameserver_datacenter_ids_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgSteamDatagramCertificate.gameserver_datacenter_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CMsgSteamDatagramCertificate::gameserver_datacenter_ids() const {
  // @@protoc_insertion_point(field_list:CMsgSteamDatagramCertificate.gameserver_datacenter_ids)
  return gameserver_datacenter_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CMsgSteamDatagramCertificate::mutable_gameserver_datacenter_ids() {
  // @@protoc_insertion_point(field_mutable_list:CMsgSteamDatagramCertificate.gameserver_datacenter_ids)
  return &gameserver_datacenter_ids_;
}

// optional fixed32 time_created = 8;
inline bool CMsgSteamDatagramCertificate::has_time_created() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_time_created() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CMsgSteamDatagramCertificate::clear_has_time_created() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CMsgSteamDatagramCertificate::clear_time_created() {
  time_created_ = 0u;
  clear_has_time_created();
}
inline ::google::protobuf::uint32 CMsgSteamDatagramCertificate::time_created() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.time_created)
  return time_created_;
}
inline void CMsgSteamDatagramCertificate::set_time_created(::google::protobuf::uint32 value) {
  set_has_time_created();
  time_created_ = value;
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.time_created)
}

// optional fixed32 time_expiry = 9;
inline bool CMsgSteamDatagramCertificate::has_time_expiry() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CMsgSteamDatagramCertificate::set_has_time_expiry() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CMsgSteamDatagramCertificate::clear_has_time_expiry() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CMsgSteamDatagramCertificate::clear_time_expiry() {
  time_expiry_ = 0u;
  clear_has_time_expiry();
}
inline ::google::protobuf::uint32 CMsgSteamDatagramCertificate::time_expiry() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.time_expiry)
  return time_expiry_;
}
inline void CMsgSteamDatagramCertificate::set_time_expiry(::google::protobuf::uint32 value) {
  set_has_time_expiry();
  time_expiry_ = value;
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.time_expiry)
}

// repeated uint32 app_ids = 10;
inline int CMsgSteamDatagramCertificate::app_ids_size() const {
  return app_ids_.size();
}
inline void CMsgSteamDatagramCertificate::clear_app_ids() {
  app_ids_.Clear();
}
inline ::google::protobuf::uint32 CMsgSteamDatagramCertificate::app_ids(int index) const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificate.app_ids)
  return app_ids_.Get(index);
}
inline void CMsgSteamDatagramCertificate::set_app_ids(int index, ::google::protobuf::uint32 value) {
  app_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificate.app_ids)
}
inline void CMsgSteamDatagramCertificate::add_app_ids(::google::protobuf::uint32 value) {
  app_ids_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgSteamDatagramCertificate.app_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CMsgSteamDatagramCertificate::app_ids() const {
  // @@protoc_insertion_point(field_list:CMsgSteamDatagramCertificate.app_ids)
  return app_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CMsgSteamDatagramCertificate::mutable_app_ids() {
  // @@protoc_insertion_point(field_mutable_list:CMsgSteamDatagramCertificate.app_ids)
  return &app_ids_;
}

// -------------------------------------------------------------------

// CMsgSteamDatagramCertificateSigned

// optional bytes cert = 4;
inline bool CMsgSteamDatagramCertificateSigned::has_cert() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgSteamDatagramCertificateSigned::set_has_cert() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_has_cert() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_cert() {
  cert_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cert();
}
inline const ::std::string& CMsgSteamDatagramCertificateSigned::cert() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificateSigned.cert)
  return cert_.GetNoArena();
}
inline void CMsgSteamDatagramCertificateSigned::set_cert(const ::std::string& value) {
  set_has_cert();
  cert_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificateSigned.cert)
}
#if LANG_CXX11
inline void CMsgSteamDatagramCertificateSigned::set_cert(::std::string&& value) {
  set_has_cert();
  cert_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamDatagramCertificateSigned.cert)
}
#endif
inline void CMsgSteamDatagramCertificateSigned::set_cert(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cert();
  cert_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamDatagramCertificateSigned.cert)
}
inline void CMsgSteamDatagramCertificateSigned::set_cert(const void* value, size_t size) {
  set_has_cert();
  cert_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamDatagramCertificateSigned.cert)
}
inline ::std::string* CMsgSteamDatagramCertificateSigned::mutable_cert() {
  set_has_cert();
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificateSigned.cert)
  return cert_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamDatagramCertificateSigned::release_cert() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificateSigned.cert)
  clear_has_cert();
  return cert_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamDatagramCertificateSigned::set_allocated_cert(::std::string* cert) {
  if (cert != NULL) {
    set_has_cert();
  } else {
    clear_has_cert();
  }
  cert_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cert);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificateSigned.cert)
}

// optional fixed64 ca_key_id = 5;
inline bool CMsgSteamDatagramCertificateSigned::has_ca_key_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgSteamDatagramCertificateSigned::set_has_ca_key_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_has_ca_key_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_ca_key_id() {
  ca_key_id_ = GOOGLE_ULONGLONG(0);
  clear_has_ca_key_id();
}
inline ::google::protobuf::uint64 CMsgSteamDatagramCertificateSigned::ca_key_id() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificateSigned.ca_key_id)
  return ca_key_id_;
}
inline void CMsgSteamDatagramCertificateSigned::set_ca_key_id(::google::protobuf::uint64 value) {
  set_has_ca_key_id();
  ca_key_id_ = value;
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificateSigned.ca_key_id)
}

// optional bytes ca_signature = 6;
inline bool CMsgSteamDatagramCertificateSigned::has_ca_signature() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgSteamDatagramCertificateSigned::set_has_ca_signature() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_has_ca_signature() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_ca_signature() {
  ca_signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ca_signature();
}
inline const ::std::string& CMsgSteamDatagramCertificateSigned::ca_signature() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificateSigned.ca_signature)
  return ca_signature_.GetNoArena();
}
inline void CMsgSteamDatagramCertificateSigned::set_ca_signature(const ::std::string& value) {
  set_has_ca_signature();
  ca_signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificateSigned.ca_signature)
}
#if LANG_CXX11
inline void CMsgSteamDatagramCertificateSigned::set_ca_signature(::std::string&& value) {
  set_has_ca_signature();
  ca_signature_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamDatagramCertificateSigned.ca_signature)
}
#endif
inline void CMsgSteamDatagramCertificateSigned::set_ca_signature(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_ca_signature();
  ca_signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamDatagramCertificateSigned.ca_signature)
}
inline void CMsgSteamDatagramCertificateSigned::set_ca_signature(const void* value, size_t size) {
  set_has_ca_signature();
  ca_signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamDatagramCertificateSigned.ca_signature)
}
inline ::std::string* CMsgSteamDatagramCertificateSigned::mutable_ca_signature() {
  set_has_ca_signature();
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificateSigned.ca_signature)
  return ca_signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamDatagramCertificateSigned::release_ca_signature() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificateSigned.ca_signature)
  clear_has_ca_signature();
  return ca_signature_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamDatagramCertificateSigned::set_allocated_ca_signature(::std::string* ca_signature) {
  if (ca_signature != NULL) {
    set_has_ca_signature();
  } else {
    clear_has_ca_signature();
  }
  ca_signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ca_signature);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificateSigned.ca_signature)
}

// optional bytes private_key_data = 1;
inline bool CMsgSteamDatagramCertificateSigned::has_private_key_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgSteamDatagramCertificateSigned::set_has_private_key_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_has_private_key_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgSteamDatagramCertificateSigned::clear_private_key_data() {
  private_key_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_private_key_data();
}
inline const ::std::string& CMsgSteamDatagramCertificateSigned::private_key_data() const {
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificateSigned.private_key_data)
  return private_key_data_.GetNoArena();
}
inline void CMsgSteamDatagramCertificateSigned::set_private_key_data(const ::std::string& value) {
  set_has_private_key_data();
  private_key_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgSteamDatagramCertificateSigned.private_key_data)
}
#if LANG_CXX11
inline void CMsgSteamDatagramCertificateSigned::set_private_key_data(::std::string&& value) {
  set_has_private_key_data();
  private_key_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgSteamDatagramCertificateSigned.private_key_data)
}
#endif
inline void CMsgSteamDatagramCertificateSigned::set_private_key_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_private_key_data();
  private_key_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgSteamDatagramCertificateSigned.private_key_data)
}
inline void CMsgSteamDatagramCertificateSigned::set_private_key_data(const void* value, size_t size) {
  set_has_private_key_data();
  private_key_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgSteamDatagramCertificateSigned.private_key_data)
}
inline ::std::string* CMsgSteamDatagramCertificateSigned::mutable_private_key_data() {
  set_has_private_key_data();
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificateSigned.private_key_data)
  return private_key_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgSteamDatagramCertificateSigned::release_private_key_data() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificateSigned.private_key_data)
  clear_has_private_key_data();
  return private_key_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgSteamDatagramCertificateSigned::set_allocated_private_key_data(::std::string* private_key_data) {
  if (private_key_data != NULL) {
    set_has_private_key_data();
  } else {
    clear_has_private_key_data();
  }
  private_key_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), private_key_data);
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificateSigned.private_key_data)
}

// -------------------------------------------------------------------

// CMsgSteamDatagramCertificateRequest

// optional .CMsgSteamDatagramCertificate cert = 1;
inline bool CMsgSteamDatagramCertificateRequest::has_cert() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgSteamDatagramCertificateRequest::set_has_cert() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgSteamDatagramCertificateRequest::clear_has_cert() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgSteamDatagramCertificateRequest::clear_cert() {
  if (cert_ != NULL) cert_->Clear();
  clear_has_cert();
}
inline const ::CMsgSteamDatagramCertificate& CMsgSteamDatagramCertificateRequest::cert() const {
  const ::CMsgSteamDatagramCertificate* p = cert_;
  // @@protoc_insertion_point(field_get:CMsgSteamDatagramCertificateRequest.cert)
  return p != NULL ? *p : *reinterpret_cast<const ::CMsgSteamDatagramCertificate*>(
      &::_CMsgSteamDatagramCertificate_default_instance_);
}
inline ::CMsgSteamDatagramCertificate* CMsgSteamDatagramCertificateRequest::release_cert() {
  // @@protoc_insertion_point(field_release:CMsgSteamDatagramCertificateRequest.cert)
  clear_has_cert();
  ::CMsgSteamDatagramCertificate* temp = cert_;
  cert_ = NULL;
  return temp;
}
inline ::CMsgSteamDatagramCertificate* CMsgSteamDatagramCertificateRequest::mutable_cert() {
  set_has_cert();
  if (cert_ == NULL) {
    cert_ = new ::CMsgSteamDatagramCertificate;
  }
  // @@protoc_insertion_point(field_mutable:CMsgSteamDatagramCertificateRequest.cert)
  return cert_;
}
inline void CMsgSteamDatagramCertificateRequest::set_allocated_cert(::CMsgSteamDatagramCertificate* cert) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete cert_;
  }
  if (cert) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      cert = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, cert, submessage_arena);
    }
    set_has_cert();
  } else {
    clear_has_cert();
  }
  cert_ = cert;
  // @@protoc_insertion_point(field_set_allocated:CMsgSteamDatagramCertificateRequest.cert)
}

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::CMsgSteamDatagramCertificate_EKeyType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CMsgSteamDatagramCertificate_EKeyType>() {
  return ::CMsgSteamDatagramCertificate_EKeyType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_steamnetworkingsockets_5fmessages_5fcerts_2eproto__INCLUDED
